# Generated by Django 4.2.3 on 2023-08-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Move_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('payscale', models.CharField(max_length=50)),
                ('cnic_no', models.CharField(max_length=15)),
                ('passport', models.CharField(blank=True, max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('project', models.CharField(max_length=50)),
                ('time_of_move', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('night', 'Night')], max_length=10)),
                ('time_of_return', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('night', 'Night')], max_length=10)),
                ('mode_of_travel', models.CharField(choices=[('Air', 'Air'), ('Bus', 'Bus'), ('Road', 'Road'), ('Train', 'Train')], max_length=10)),
                ('date_of_moves', models.DateField()),
                ('date_of_return', models.DateField()),
                ('route', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Official', 'Official'), ('Private', 'Private'), ('Open', 'Open'), ('Classified', 'Classified')], max_length=20)),
                ('pov', models.TextField()),
                ('duration_days', models.IntegerField()),
                ('duration_nights', models.IntegerField()),
                ('relatedpro', models.CharField(max_length=50)),
                ('fundingsources', models.TextField(blank=True)),
                ('advance', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
            ],
        ),
    ]
